CREATE TABLE gahyeon_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    schema_version INTEGER NOT NULL,
    event_type VARCHAR(120) NOT NULL,
    session_id VARCHAR(200) NOT NULL,
    correlation_id VARCHAR(120) NOT NULL,
    payload_json TEXT NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_gahyeon_events_session_sequence
    ON gahyeon_events(session_id, id);
